Email sent successfully!
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/Half_Earthaug17Batch/0.49595959595959593'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/Half_Earthaug17Batch/0.5'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "massListSorter.py", line 52, in <module>
    massListSorter(sys.argv[2])
  File "massListSorter.py", line 30, in massListSorter
    file.write('\n')
OSError: [Errno 122] Disk quota exceeded
Sat Aug 28 12:49:48 EDT 2021
